import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { serializeEnvironmentFile } from '../../../../../cli/core/environment-file'
import { ensureAttentionEnvironment } from '../../../../../server/modules/attention/adapters/attention-environment'
import { createEnvironmentFixture } from '../../../../cli/support/release-fixture'

const directories: string[] = []
afterEach(() => directories.splice(0).forEach(path => rmSync(path, { force: true, recursive: true })))

describe('ensureAttentionEnvironment', () => {
  it('uses ephemeral secrets without rewriting a legacy development environment', () => {
    const root = mkdtempSync(join(tmpdir(), 'bitveins-attention-env-'))
    directories.push(root)
    const path = join(root, 'env')
    const legacy = serializeEnvironmentFile(createEnvironmentFixture())
      .split('\n')
      .filter(line => !line.startsWith('BITVEINS_EVENT_TOKEN='))
      .filter(line => !line.startsWith('BITVEINS_VAPID_'))
      .join('\n')
    writeFileSync(path, legacy, { mode: 0o600 })
    const environment: NodeJS.ProcessEnv = {}

    const secrets = ensureAttentionEnvironment(environment, { environmentFile: path })

    expect(environment.BITVEINS_EVENT_TOKEN).toBe(secrets.eventToken)
    expect(readFileSync(path, 'utf8')).not.toContain('BITVEINS_VAPID_PRIVATE_KEY=')
    expect(statSync(path).mode & 0o777).toBe(0o600)
  })

  it('rejects missing or publicly readable production configuration', () => {
    const root = mkdtempSync(join(tmpdir(), 'bitveins-attention-env-'))
    directories.push(root)
    const path = join(root, 'env')
    expect(() => ensureAttentionEnvironment(
      { NODE_ENV: 'production' },
      { environmentFile: path },
    )).toThrow('production attention secrets require a private environment file')

    writeFileSync(path, serializeEnvironmentFile(createEnvironmentFixture()), { mode: 0o644 })
    const configured = createEnvironmentFixture()
    expect(() => ensureAttentionEnvironment(
      {
        BITVEINS_EVENT_TOKEN: configured.eventToken,
        BITVEINS_VAPID_PRIVATE_KEY: configured.vapidPrivateKey,
        BITVEINS_VAPID_PUBLIC_KEY: configured.vapidPublicKey,
        NODE_ENV: 'production',
      },
      { environmentFile: path },
    )).toThrow('environment file must be a private regular file')
  })

  it('requires the installer or updater to migrate a private production configuration', () => {
    const root = mkdtempSync(join(tmpdir(), 'bitveins-attention-env-'))
    directories.push(root)
    const path = join(root, 'env')
    const legacy = serializeEnvironmentFile(createEnvironmentFixture())
      .split('\n')
      .filter(line => !line.startsWith('BITVEINS_EVENT_TOKEN='))
      .filter(line => !line.startsWith('BITVEINS_VAPID_'))
      .join('\n')
    writeFileSync(path, legacy, { mode: 0o600 })

    expect(() => ensureAttentionEnvironment(
      { NODE_ENV: 'production' },
      { environmentFile: path },
    )).toThrow('must be generated by the installer or updater')
  })
})
