import { lstatSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { generateAttentionSecrets, migrateAttentionSecrets, type AttentionSecrets } from '#shared/security/attention-secrets'

export function ensureAttentionEnvironment(
  environment: NodeJS.ProcessEnv = process.env,
  options: { environmentFile?: string } = {},
): AttentionSecrets {
  const environmentFile = options.environmentFile ?? join(
    environment.XDG_CONFIG_HOME || join(homedir(), '.config'),
    'bitveins',
    'env',
  )
  const configured = readConfiguredSecrets(environment)
  if (environment.NODE_ENV !== 'production' && configured) return configured

  try {
    if (environment.NODE_ENV === 'production') assertPrivateConfiguration(environmentFile)
    const content = readFileSync(environmentFile, 'utf8')
    const migration = migrateAttentionSecrets(content)
    if (environment.NODE_ENV === 'production' && migration.content !== content) {
      throw new Error('Bitveins production attention secrets must be generated by the installer or updater.')
    }
    const secrets = migration.secrets
    if (configured && !sameSecrets(configured, secrets)) {
      throw new Error('Bitveins process secrets do not match the private environment file.')
    }
    apply(environment, secrets)
    return secrets
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    if (environment.NODE_ENV === 'production') {
      throw new Error('Bitveins production attention secrets require a private environment file.', { cause: error })
    }
    const secrets = generateAttentionSecrets()
    apply(environment, secrets)
    return secrets
  }
}

function sameSecrets(left: AttentionSecrets, right: AttentionSecrets): boolean {
  return left.eventToken === right.eventToken
    && left.vapidPrivateKey === right.vapidPrivateKey
    && left.vapidPublicKey === right.vapidPublicKey
}

function assertPrivateConfiguration(environmentFile: string): void {
  const directory = lstatSync(dirname(environmentFile))
  const file = lstatSync(environmentFile)
  const uid = process.getuid?.()
  if (!directory.isDirectory() || directory.isSymbolicLink() || (directory.mode & 0o077) !== 0) {
    throw new Error('Bitveins configuration directory must be a private directory.')
  }
  if (!file.isFile() || file.isSymbolicLink() || (file.mode & 0o077) !== 0) {
    throw new Error('Bitveins environment file must be a private regular file.')
  }
  if (uid !== undefined && (directory.uid !== uid || file.uid !== uid)) {
    throw new Error('Bitveins configuration must be owned by the current user.')
  }
}

function readConfiguredSecrets(environment: NodeJS.ProcessEnv): AttentionSecrets | null {
  const eventToken = environment.BITVEINS_EVENT_TOKEN
  const vapidPrivateKey = environment.BITVEINS_VAPID_PRIVATE_KEY
  const vapidPublicKey = environment.BITVEINS_VAPID_PUBLIC_KEY
  const values = [eventToken, vapidPrivateKey, vapidPublicKey]
  if (values.every(Boolean)) {
    return { eventToken: eventToken!, vapidPrivateKey: vapidPrivateKey!, vapidPublicKey: vapidPublicKey! }
  }
  if (values.some(Boolean)) {
    throw new Error('Bitveins attention secrets must be configured together.')
  }
  return null
}

function apply(environment: NodeJS.ProcessEnv, secrets: AttentionSecrets): void {
  environment.BITVEINS_EVENT_TOKEN = secrets.eventToken
  environment.BITVEINS_VAPID_PRIVATE_KEY = secrets.vapidPrivateKey
  environment.BITVEINS_VAPID_PUBLIC_KEY = secrets.vapidPublicKey
}
