import { randomBytes } from 'node:crypto'
import { CliConfigurationError } from './cli-error'

export interface BitveinsEnvironment {
  readonly allowedOrigins: readonly string[]
  readonly authPasswordHash: string
  readonly authVersion: string
  readonly databasePath: string
  readonly extensions: Readonly<Record<string, string>>
  readonly host: string
  readonly port: number
  readonly sessionPassword: string
}

const environmentKeys = {
  allowedOrigins: 'BITVEINS_ALLOWED_ORIGINS',
  authPasswordHash: 'BITVEINS_AUTH_PASSWORD_HASH',
  authVersion: 'BITVEINS_AUTH_VERSION',
  databasePath: 'BITVEINS_DATABASE_PATH',
  host: 'HOST',
  port: 'PORT',
  sessionPassword: 'NUXT_SESSION_PASSWORD',
} as const

const knownKeys = new Set<string>(Object.values(environmentKeys))
const keyPattern = /^[A-Z][A-Z0-9_]*$/
const safeValuePattern = /^[^\n\r\0]*$/
const portPattern = /^\d{1,5}$/

function assertEnvironmentValue(key: string, value: string): void {
  if (!keyPattern.test(key)) {
    throw new CliConfigurationError(`Invalid environment key: ${key}`)
  }
  if (!safeValuePattern.test(value)) {
    throw new CliConfigurationError(
      `Environment value for ${key} contains an unsupported character.`,
    )
  }
}

function unquote(value: string): string {
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return value
      .slice(1, -1)
      .replaceAll('\\"', '"')
      .replaceAll('\\\\', '\\')
  }
  return value
}

function quote(value: string): string {
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`
}

function required(
  values: Readonly<Record<string, string>>,
  key: string,
): string {
  const value = values[key]
  if (!value) {
    throw new CliConfigurationError(
      `Required Bitveins environment value ${key} is missing.`,
    )
  }
  return value
}

function parseRawEnvironment(content: string): Record<string, string> {
  const values: Record<string, string> = {}

  for (const [index, sourceLine] of content.split(/\r?\n/u).entries()) {
    const line = sourceLine.trim()
    if (!line || line.startsWith('#')) {
      continue
    }

    const separator = line.indexOf('=')
    if (separator < 1) {
      throw new CliConfigurationError(
        `Invalid environment file line ${index + 1}.`,
      )
    }

    const key = line.slice(0, separator)
    const value = unquote(line.slice(separator + 1))
    assertEnvironmentValue(key, value)
    values[key] = value
  }

  return values
}

export function parseEnvironmentFile(content: string): BitveinsEnvironment {
  const values = parseRawEnvironment(content)
  const extensions = Object.fromEntries(
    Object.entries(values).filter(([key]) => !knownKeys.has(key)),
  )

  return {
    allowedOrigins: required(values, environmentKeys.allowedOrigins)
      .split(',')
      .filter(Boolean),
    authPasswordHash: required(values, environmentKeys.authPasswordHash),
    authVersion: required(values, environmentKeys.authVersion),
    databasePath: required(values, environmentKeys.databasePath),
    extensions,
    host: required(values, environmentKeys.host),
    port: parseBitveinsPort(required(values, environmentKeys.port)),
    sessionPassword: required(values, environmentKeys.sessionPassword),
  }
}

export function serializeEnvironmentFile(environment: BitveinsEnvironment): string {
  const values: Record<string, string> = {
    ...environment.extensions,
    [environmentKeys.allowedOrigins]: environment.allowedOrigins.join(','),
    [environmentKeys.authPasswordHash]: environment.authPasswordHash,
    [environmentKeys.authVersion]: environment.authVersion,
    [environmentKeys.databasePath]: environment.databasePath,
    [environmentKeys.host]: environment.host,
    [environmentKeys.port]: String(parseBitveinsPort(String(environment.port))),
    [environmentKeys.sessionPassword]: environment.sessionPassword,
  }
  const lines = [
    '# Generated by Bitveins. Keep this file private.',
    ...Object.entries(values)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, value]) => {
        assertEnvironmentValue(key, value)
        return `${key}=${quote(value)}`
      }),
    '',
  ]
  return lines.join('\n')
}

export function createBitveinsEnvironment(options: {
  allowedOrigin?: string
  databasePath: string
  passwordHash: string
  port: number
}): BitveinsEnvironment {
  const port = parseBitveinsPort(String(options.port))
  const allowedOrigins = [
    `http://127.0.0.1:${port}`,
    `http://localhost:${port}`,
  ]
  if (options.allowedOrigin) {
    allowedOrigins.unshift(normalizePublicOrigin(options.allowedOrigin))
  }

  return {
    allowedOrigins,
    authPasswordHash: options.passwordHash,
    authVersion: '1',
    databasePath: options.databasePath,
    extensions: {},
    host: '127.0.0.1',
    port,
    sessionPassword: randomBytes(48).toString('base64url'),
  }
}

export function parseBitveinsPort(value: string | undefined): number {
  const candidate = value || '3000'
  if (!portPattern.test(candidate)) {
    throw new CliConfigurationError(
      'Bitveins port must be an integer between 1024 and 65535.',
    )
  }

  const port = Number(candidate)
  if (!Number.isInteger(port) || port < 1024 || port > 65535) {
    throw new CliConfigurationError(
      'Bitveins port must be an integer between 1024 and 65535.',
    )
  }
  return port
}

export function normalizePublicOrigin(value: string): string {
  const url = new URL(value)
  if (url.protocol !== 'https:') {
    throw new CliConfigurationError('The public Bitveins origin must use HTTPS.')
  }
  if (url.username || url.password || url.pathname !== '/' || url.search || url.hash) {
    throw new CliConfigurationError(
      'The public Bitveins origin must not contain credentials, a path, query or hash.',
    )
  }
  return url.origin
}

export function incrementAuthVersion(current: string): string {
  const parsed = Number.parseInt(current, 10)
  return Number.isSafeInteger(parsed) && parsed >= 1
    ? String(parsed + 1)
    : randomBytes(12).toString('hex')
}
